{% set name = "framel" %}
{% set version = "8.40.1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: http://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.xz
  sha256: ea4afcdf839f8eb49edc2d3190b5aebb08871146e426b644887f7efbae30a6b9
  patches:
    # mkdir on mingw only takes one argument
    - mkdir.patch  # [win]

build:
  error_overdepending: true
  error_overlinking: true
  number: 1

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - cmake
    - make  # [not win]
    - ninja  # [win]

outputs:
  - name: libframel
    build:
      run_exports:
        - {{ pin_subpackage("libframel", max_pin="x") }}
    requirements:
      build:
        - {{ compiler('c') }}  # [not win]
        - {{ compiler('m2w64_c') }}  # [win]
      run_constained:
        - libframe >=9999
    files:
      - include/  # [not win]
      - lib/libframel.*  # [not win]
      - lib/pkgconfig/framel.pc  # [not win]
      - Library/include/  # [win]
      - Library/bin/libframel.dll  # [win]
      - Library/lib/libframel.*  # [win]
      - Library/lib/pkgconfig/framel.pc  # [win]
    test:
      requires:
        - pkg-config  # [not win]
      commands:
        - test "$(pkg-config --print-errors --modversion framel)" == "${PKG_VERSION}"  # [not win]
    about:
      home: http://lappweb.in2p3.fr/virgo/FrameL/
      license: LGPL-2.1-or-later
      license_family: LGPL
      license_file: LICENSE
      summary: LIGO/Virgo Frame Library
      description: |
        A Common Data Frame Format for Interferometric Gravitational Wave
        Detector has been developed by VIRGO and LIGO.
        The Frame Library is a software dedicated to the frame manipulation
        including file input/output.
        This package provides the `libframel` shared library and development
        files.

  - name: framel
    requirements:
      build:
        - {{ compiler('c') }}  # [not win]
        - {{ compiler('m2w64_c') }}  # [win]
      host:
        - {{ pin_subpackage("libframel", exact=True) }}
      run:
        - {{ pin_subpackage("libframel", exact=True) }}
      run_constained:
        - libframe >=9999
    files:
      - bin/  # [not win]
      - share/doc/  # [not win]
      - Library/bin/Fr*  # [win]
      - Library/share/doc/  # [win]
    test:
      source_files:
        - data/test.gwf
      commands:
        - FrChannels data/test.gwf
        - FrCheck -i data/test.gwf
        - FrCopy -i data/test.gwf -o copy.gwf
        - FrDiff -i1 data/test.gwf -i2 copy.gwf -t D1 -d 1
        - FrDump -i data/test.gwf -t D1
        - FrCopy -i data/test.gwf -o copy2.gwf -f 0 -l 1 -r 10
        - FrTrend -s 1 -p trend- -d 5 -c D1 -f 925484670 -l 925484680 copy2.gwf
    about:
      home: http://lappweb.in2p3.fr/virgo/FrameL/
      license: LGPL-2.1-or-later
      license_family: LGPL
      license_file: LICENSE
      summary: LIGO/Virgo Frame Library
      description: |
        A Common Data Frame Format for Interferometric Gravitational Wave
        Detector has been developed by VIRGO and LIGO.
        The Frame Library is a software dedicated to the frame manipulation
        including file input/output.
        This package provides the FrameL command line utilities.

  - name: python-framel
    script: install-python.sh  # [not win]
    script: install-python.bat  # [win]
    build:
      ignore_run_exports:
        - python  # [osx]
    requirements:
      build:
        - {{ compiler('c') }}  # [not win]
        - {{ compiler('m2w64_c') }}  # [win]
        - cmake >=3.16.0
        - make  # [not win]
        - ninja  # [win]
      host:
        - {{ pin_subpackage('libframel', exact=True) }}
        - libpython  # [win]
        - numpy
        - python
      run:
        - {{ pin_subpackage('libframel', exact=True) }}
        - {{ pin_compatible('numpy') }}
        - python
    test:
      source_files:
        - data/test.gwf
      imports:
        - framel
      commands:
        - >
          python -c
          "from pathlib import Path;
          from numpy.testing import assert_array_equal;
          import framel;
          indata = framel.frgetvect1d(str(Path('data') / 'test.gwf'), 'D1');
          framel.frputvect('test2.gwf', [{'name': 'A1:TEST', 'data': indata[0], 'start': indata[1], 'dx': indata[3], 'x_unit': indata[4], 'y_unit': indata[5]}]);
          indata2 = framel.frgetvect1d('test2.gwf', 'A1:TEST');
          assert_array_equal(indata[0], indata2[0], 'read-write data mismatch');
          assert indata[1:] == indata2[1:], 'read-write metadata mismatch';
          "
    about:
      home: http://lappweb.in2p3.fr/virgo/FrameL/
      license: LGPL-2.1-or-later
      license_family: LGPL
      license_file: LICENSE
      summary: LIGO/Virgo Frame Library
      description: |
        A Common Data Frame Format for Interferometric Gravitational Wave
        Detector has been developed by VIRGO and LIGO.
        The Frame Library is a software dedicated to the frame manipulation
        including file input/output.
        This package provides the python bindings.

about:
  home: http://lappweb.in2p3.fr/virgo/FrameL/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: LIGO/Virgo Frame Library
  description: |
    A Common Data Frame Format for Interferometric Gravitational Wave
    Detector has been developed by VIRGO and LIGO.
    The Frame Library is a software dedicated to the frame manipulation
    including file input/output.
    This recipe provides packages for the `libframel` shared library,
    command line utilities, and python bindings.

extra:
  feedstock-name: framel
  recipe-maintainers:
    - duncanmmacleod
