{% set name = "framel" %}
{% set version = "8.46.1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://git.ligo.org/virgo/virgoapp/Fr/-/archive/{{ version }}/Fr-{{ version }}.tar.gz
  sha256: 707a7d671015c2525f0a3a7c759640ef87f7eed4fa7389c5a3813b27114a0585
  patches:
    # mkdir on mingw only takes one argument
    - 0001-FrIO-fix-mkdir-on-windows.patch

build:
  error_overdepending: true
  error_overlinking: true
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - cmake
    - make  # [not win]
    - ninja  # [win]

outputs:
  - name: libframel
    build:
      run_exports:
        - {{ pin_subpackage("libframel", max_pin="x") }}
      ignore_run_exports:
        - m2w64-gcc-libs  # [win]
        - m2w64-gcc-libs-core  # [win]
    requirements:
      build:
        - {{ compiler('c') }}  # [not win]
        - {{ compiler('m2w64_c') }}  # [win]
      run_constained:
        - libframe >=9999
    files:
      - include/  # [not win]
      - lib/libframel.*  # [not win]
      - lib/pkgconfig/framel.pc  # [not win]
      - Library/include/  # [win]
      - Library/bin/libframel.dll  # [win]
      - Library/lib/libframel.*  # [win]
      - Library/lib/pkgconfig/framel.pc  # [win]
    test:
      requires:
        - pkg-config  # [not win]
      commands:
        - test "$(pkg-config --print-errors --modversion framel)" == "${PKG_VERSION}"  # [not win]
    about:
      home: http://lappweb.in2p3.fr/virgo/FrameL/
      license: LGPL-2.1-or-later
      license_family: LGPL
      license_file: LICENSE
      summary: LIGO/Virgo Frame Library
      description: |
        A Common Data Frame Format for Interferometric Gravitational Wave
        Detector has been developed by VIRGO and LIGO.
        The Frame Library is a software dedicated to the frame manipulation
        including file input/output.
        This package provides the `libframel` shared library and development
        files.

  - name: framel
    build:
      ignore_run_exports:
        - m2w64-gcc-libs  # [win]
        - m2w64-gcc-libs-core  # [win]
    requirements:
      build:
        - {{ compiler('c') }}  # [not win]
        - {{ compiler('m2w64_c') }}  # [win]
      host:
        - {{ pin_subpackage("libframel", exact=True) }}
      run:
        - {{ pin_subpackage("libframel", exact=True) }}
      run_constained:
        - libframe >=9999
    files:
      - bin/  # [not win]
      - share/doc/  # [not win]
      - Library/bin/Fr*  # [win]
      - Library/share/doc/  # [win]
    test:
      source_files:
        - data/test.gwf
      commands:
        - FrChannels data/test.gwf
        - FrCheck -i data/test.gwf
        - FrCopy -i data/test.gwf -o copy.gwf
        - FrDiff -i1 data/test.gwf -i2 copy.gwf -t D1 -d 1
        - FrDump -i data/test.gwf -t D1
        - FrCopy -i data/test.gwf -o copy2.gwf -f 0 -l 1 -r 10
        - FrTrend -s 1 -p trend- -d 5 -c D1 -f 925484670 -l 925484680 copy2.gwf
    about:
      home: http://lappweb.in2p3.fr/virgo/FrameL/
      license: LGPL-2.1-or-later
      license_family: LGPL
      license_file: LICENSE
      summary: LIGO/Virgo Frame Library
      description: |
        A Common Data Frame Format for Interferometric Gravitational Wave
        Detector has been developed by VIRGO and LIGO.
        The Frame Library is a software dedicated to the frame manipulation
        including file input/output.
        This package provides the FrameL command line utilities.

  - name: python-framel
    script: install-python.sh  # [not win]
    script: install-python.bat  # [win]
    build:
      ignore_run_exports:
        - m2w64-gcc-libs  # [win]
        - m2w64-gcc-libs-core  # [win]
        - numpy
        - python  # [osx]
      skip: true  # [win or python_impl != 'cpython']
    requirements:
      build:
        - {{ compiler('c') }}  # [not win]
        - {{ compiler('m2w64_c') }}  # [win]
        - cmake >=3.16.0
        - make  # [not win]
        - ninja  # [win]
        # extras for cross-compiling
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - ctypesgen
      host:
        - {{ pin_subpackage('libframel', exact=True) }}
        - libpython  # [win]
        - numpy
        - python
      run:
        - {{ pin_subpackage('libframel', exact=True) }}
        - {{ pin_compatible('numpy') }}
        - python
    test:
      requires:
        - pip
        - pytest
      source_files:
        - test/
      commands:
        # check metadata
        - python -m pip check
        - python -m pip show framel
        # run test suite
        - python -m pytest test -ra
    about:
      home: http://lappweb.in2p3.fr/virgo/FrameL/
      license: LGPL-2.1-or-later
      license_family: LGPL
      license_file: LICENSE
      summary: LIGO/Virgo Frame Library
      description: |
        A Common Data Frame Format for Interferometric Gravitational Wave
        Detector has been developed by VIRGO and LIGO.
        The Frame Library is a software dedicated to the frame manipulation
        including file input/output.
        This package provides the python bindings.

about:
  home: http://lappweb.in2p3.fr/virgo/FrameL/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: LIGO/Virgo Frame Library
  description: |
    A Common Data Frame Format for Interferometric Gravitational Wave
    Detector has been developed by VIRGO and LIGO.
    The Frame Library is a software dedicated to the frame manipulation
    including file input/output.
    This recipe provides packages for the `libframel` shared library,
    command line utilities, and python bindings.

extra:
  feedstock-name: framel
  recipe-maintainers:
    - duncanmmacleod
    - anthchirp
    - rhyspoulton
